name: ci

on: [push, pull_request_target]

env:
  MY_SECRET: ${{ secrets.MY_SECRET }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      if: ${{ github.event_name != 'pull_request_target' }}
    - uses: actions/checkout@v2
      if: ${{ github.event_name == 'pull_request_target' }}
      with:
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}
    - name: Install
      run: |
        npm install
